export const EXPERIENCE_DATA = [
  {
    title: "Senior Software Engineer",
    company: "Mastercard",
    duration: "Sept 2019 - Present",
    color: "bg-[#667EEA]",
    responsibilities: [
      "Led development of high-volume payment processing systems handling 10M+ transactions daily",
      "Architected microservices using Spring Boot and deployed on AWS infrastructure",
      "Implemented real-time fraud detection systems using Kafka and machine learning",
      "Mentored junior developers and established best practices for secure coding",
    ],
  },
  {
    title: "Software Engineer",
    company: "Zensar Technologies",
    duration: "Oct 2018 - Sept 2019",
    color: "bg-[#764BA2]",
    responsibilities: [
      "Developed enterprise web applications using Angular and React",
      "Integrated RESTful APIs and implemented responsive UI components",
      "Collaborated with cross-functional teams in agile development environment",
      "Optimized application performance and improved user experience",
    ],
  },
  {
    title: "Junior Software Engineer",
    company: "BSOL Systems",
    duration: "Sept 2017 - March 2018",
    color: "bg-[#38BDF8]",
    responsibilities: [
      "Built web applications using Java Spring framework and MySQL",
      "Implemented unit testing and participated in code reviews",
      "Learned software development lifecycle and version control with Git",
      "Contributed to documentation and technical specifications",
    ],
  },
];

export const SKILLS_DATA = [
  {
    category: "Backend",
    icon: "Server",
    color: "text-[#667EEA]",
    skills: [
      { name: "Spring Boot", level: 5 },
      { name: "Java", level: 4 },
      { name: "Kafka", level: 4 },
    ],
  },
  {
    category: "Frontend",
    icon: "Code",
    color: "text-[#F093FB]",
    skills: [
      { name: "React", level: 5 },
      { name: "Angular", level: 4 },
      { name: "TypeScript", level: 4 },
    ],
  },
  {
    category: "Cloud & DevOps",
    icon: "Cloud",
    color: "text-[#38BDF8]",
    skills: [
      { name: "AWS", level: 4 },
      { name: "Docker", level: 4 },
      { name: "Jenkins", level: 4 },
    ],
  },
];

export const PROJECTS_DATA = [
  {
    title: "Alexa Jenkins Pipeline Integration",
    description: "Revolutionary voice-controlled CI/CD pipeline management system that allows developers to trigger builds, check deployment status, and manage Jenkins jobs using Amazon Alexa voice commands.",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=800&h=400",
    technologies: ["AWS Lambda", "Alexa Skills", "Jenkins API", "Node.js"],
    techColors: [
      "bg-[#667EEA]/20 text-[#667EEA]",
      "bg-[#667EEA]/20 text-[#667EEA]",
      "bg-[#667EEA]/20 text-[#667EEA]",
      "bg-[#667EEA]/20 text-[#667EEA]",
    ],
    primaryButtonText: "Code",
    secondaryButtonText: "Demo",
    primaryButtonStyle: "bg-gradient-to-r from-[#667EEA] to-[#764BA2] hover:shadow-lg hover:shadow-[#667EEA]/30",
    primaryIcon: "Github",
    secondaryIcon: "ExternalLink",
  },
  {
    title: "VaccineMan Telegram Bot",
    description: "Intelligent Telegram bot that helps users find available COVID-19 vaccination slots in their area, sends real-time notifications, and provides vaccination center information and booking assistance.",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=800&h=400",
    technologies: ["Python", "Telegram API", "REST APIs", "MongoDB"],
    techColors: [
      "bg-[#F093FB]/20 text-[#F093FB]",
      "bg-[#F093FB]/20 text-[#F093FB]",
      "bg-[#F093FB]/20 text-[#F093FB]",
      "bg-[#F093FB]/20 text-[#F093FB]",
    ],
    primaryButtonText: "Code",
    secondaryButtonText: "Live Bot",
    primaryButtonStyle: "bg-gradient-to-r from-[#F093FB] to-[#764BA2] hover:shadow-lg hover:shadow-[#F093FB]/30",
    primaryIcon: "Github",
    secondaryIcon: "ExternalLink",
  },
  {
    title: "Secure Payment Gateway",
    description: "Enterprise-grade payment processing system with advanced fraud detection, multi-currency support, and PCI DSS compliance handling millions of transactions with 99.9% uptime.",
    image: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=800&h=400",
    technologies: ["Spring Boot", "Kafka", "PostgreSQL", "AWS"],
    techColors: [
      "bg-[#38BDF8]/20 text-[#38BDF8]",
      "bg-[#38BDF8]/20 text-[#38BDF8]",
      "bg-[#38BDF8]/20 text-[#38BDF8]",
      "bg-[#38BDF8]/20 text-[#38BDF8]",
    ],
    primaryButtonText: "Case Study",
    secondaryButtonText: "Metrics",
    primaryButtonStyle: "bg-gradient-to-r from-[#38BDF8] to-[#764BA2] hover:shadow-lg hover:shadow-[#38BDF8]/30",
    primaryIcon: "Lock",
    secondaryIcon: "Activity",
  },
  {
    title: "Cloud-Native Microservices",
    description: "Scalable microservices architecture deployed on AWS with containerized services, service mesh, and automated CI/CD pipelines supporting high-availability financial applications.",
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=800&h=400",
    technologies: ["Docker", "Kubernetes", "AWS ECS", "Istio"],
    techColors: [
      "bg-[#764BA2]/20 text-[#764BA2]",
      "bg-[#764BA2]/20 text-[#764BA2]",
      "bg-[#764BA2]/20 text-[#764BA2]",
      "bg-[#764BA2]/20 text-[#764BA2]",
    ],
    primaryButtonText: "Architecture",
    secondaryButtonText: "Documentation",
    primaryButtonStyle: "bg-gradient-to-r from-[#764BA2] to-[#667EEA] hover:shadow-lg hover:shadow-[#764BA2]/30",
    primaryIcon: "Table",
    secondaryIcon: "GitBranch",
  },
];

export const SEARCH_DATA = [
  {
    title: "Senior Software Engineer at Mastercard",
    content: "Led development of high-volume payment processing systems handling 10M+ transactions daily. Architected microservices using Spring Boot and deployed on AWS infrastructure.",
    category: "Experience",
    tags: ["mastercard", "senior", "payment", "microservices", "aws"],
    anchor: "#experience",
  },
  {
    title: "Software Engineer at Zensar Technologies",
    content: "Developed enterprise web applications using Angular and React. Integrated RESTful APIs and implemented responsive UI components.",
    category: "Experience",
    tags: ["zensar", "angular", "react", "apis", "ui"],
    anchor: "#experience",
  },
  {
    title: "Junior Software Engineer at BSOL Systems",
    content: "Built web applications using Java Spring framework and MySQL. Implemented unit testing and participated in code reviews.",
    category: "Experience",
    tags: ["bsol", "java", "spring", "mysql", "testing"],
    anchor: "#experience",
  },
  {
    title: "Spring Boot",
    content: "Expert level proficiency in Spring Boot framework for building microservices and enterprise applications.",
    category: "Skills",
    tags: ["spring", "boot", "java", "microservices", "backend"],
    anchor: "#skills",
  },
  {
    title: "React",
    content: "Advanced React development skills for building modern, interactive user interfaces and single-page applications.",
    category: "Skills",
    tags: ["react", "javascript", "frontend", "ui", "spa"],
    anchor: "#skills",
  },
  {
    title: "AWS",
    content: "Cloud architecture and deployment expertise using Amazon Web Services for scalable applications.",
    category: "Skills",
    tags: ["aws", "cloud", "devops", "deployment", "scalable"],
    anchor: "#skills",
  },
  {
    title: "Alexa Jenkins Pipeline Integration",
    content: "Revolutionary voice-controlled CI/CD pipeline management system that allows developers to trigger builds, check deployment status, and manage Jenkins jobs using Amazon Alexa voice commands.",
    category: "Projects",
    tags: ["alexa", "jenkins", "ci/cd", "voice", "automation"],
    anchor: "#projects",
  },
  {
    title: "VaccineMan Telegram Bot",
    content: "Intelligent Telegram bot that helps users find available COVID-19 vaccination slots in their area, sends real-time notifications, and provides vaccination center information.",
    category: "Projects",
    tags: ["telegram", "bot", "covid", "vaccination", "healthcare"],
    anchor: "#projects",
  },
  {
    title: "Secure Payment Gateway",
    content: "Enterprise-grade payment processing system with advanced fraud detection, multi-currency support, and PCI DSS compliance handling millions of transactions.",
    category: "Projects",
    tags: ["payment", "security", "fraud", "fintech", "enterprise"],
    anchor: "#projects",
  },
  {
    title: "Cloud-Native Microservices",
    content: "Scalable microservices architecture deployed on AWS with containerized services, service mesh, and automated CI/CD pipelines supporting high-availability financial applications.",
    category: "Projects",
    tags: ["microservices", "cloud", "docker", "kubernetes", "fintech"],
    anchor: "#projects",
  },
];
